import os
from typing import List

FILEPATH="to_dos.txt"

def get_todos(filename: str = FILEPATH) -> List[str]:
    """Reads the to-dos from a file and returns them as a list.

    Args:
        filename (str, optional): The file contains the generated by the user the list of to-dos. Defaults to FILEPATH.

    Returns:
        List[str]: list of to-dos
    """
    script_dir = os.path.dirname(__file__)
    to_dos_file = os.path.join(script_dir, filename)
    to_dos_local: List[str]

    if not os.path.exists(to_dos_file):
        to_dos_local = []
        file = open(to_dos_file, "w")
        file.close()
    else:
        with open(to_dos_file, "r") as file:
            to_dos_local = file.readlines()
            to_dos_local = [item.strip() for item in to_dos_local]
    return to_dos_local


def write_todos(to_dos_local: List[str], filename: str = FILEPATH) -> None:
    """Writes the to-dos to a file.

    Args:
        to_dos_local (List[str]): list of to-dos
        filename (str, optional): The file contains the generated by the user the list of to-dos. Defaults to FILEPATH.
    """
    script_dir = os.path.dirname(__file__)
    to_dos_file = os.path.join(script_dir, filename)

    with open(to_dos_file, "w") as file:
        for item in to_dos_local:
            file.write(item + "\n")
